apiVersion: v1
kind: Service
metadata:
  name: cortex
  labels:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/component: hypergraph
spec:
  type: ClusterIP
  ports:
    - name: cell
      port: 27492
      targetPort: cell
      protocol: TCP
  selector:
    app.kubernetes.io/name: cortex
