apiVersion: v1
kind: Service
metadata:
  name: aha
  labels:
    app.kubernetes.io/name: aha
    app.kubernetes.io/component: service-discovery
spec:
  type: ClusterIP
  ports:
    - name: cell
      port: 27492
      targetPort: cell
      protocol: TCP
    - name: provision
      port: 27272
      targetPort: provision
      protocol: TCP
  selector:
    app.kubernetes.io/name: aha
