apiVersion: v1
kind: Service
metadata:
  name: axon
  labels:
    app.kubernetes.io/name: axon
    app.kubernetes.io/component: binary-storage
spec:
  type: ClusterIP
  ports:
    - name: cell
      port: 27492
      targetPort: cell
      protocol: TCP
  selector:
    app.kubernetes.io/name: axon
---
apiVersion: v1
kind: Service
metadata:
  name: axon-headless
  labels:
    app.kubernetes.io/name: axon
    app.kubernetes.io/component: binary-storage
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: cell
      port: 27492
      targetPort: cell
      protocol: TCP
  selector:
    app.kubernetes.io/name: axon
