apiVersion: v1
kind: Service
metadata:
  name: jsonstor
  labels:
    app.kubernetes.io/name: jsonstor
    app.kubernetes.io/component: json-storage
spec:
  type: ClusterIP
  ports:
    - name: cell
      port: 27492
      targetPort: cell
      protocol: TCP
  selector:
    app.kubernetes.io/name: jsonstor
